// <auto-generated />
namespace RomeoConnection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Typocorrection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Typocorrection));
        
        string IMigrationMetadata.Id
        {
            get { return "201812291230461_Typo correction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
